name: Client CI
run-name: ${{ github.actor }} is running Client CI
on:
  push:
    paths-ignore:
      - 'server/**'
jobs:
  Client-CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run build with Gradle Wrapper
        run: ./gradlew client:build
